import sharedConfig from '../config.json';

export const NONA_CONFIG = {
  app: {
    name: sharedConfig.app.name,
    slug: sharedConfig.app.slug,
    version: sharedConfig.app.version,
    platform: sharedConfig.app.platform as 'android',
    android: {
      package: sharedConfig.app.androidPackage,
      minSdkVersion: sharedConfig.app.androidMinSdkVersion,
    },
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'tl', 'ceb'] as const,
  },
  api: {
    prefix: '/api',
    routes: {
      health: '/health',
      profile: '/profile',
      transactions: '/transactions',
      assessTransaction: '/assess',
    },
  },
  transactions: {
    types: ['payment', 'load', 'transfer'] as const,
    statuses: ['pending', 'completed', 'failed', 'blocked'] as const,
    maxAmount: 1_000_000,
    maxHistoryItems: 50,
    maxRecipientLabelLength: 120,
    maxRecipientReferenceLength: 120,
    fraud: {
      highAmountThreshold: 10_000,
      highAmountScore: 35,
      newRecipientScore: 30,
      urgencyScore: 25,
      missingRecipientScore: 15,
      blockThreshold: 70,
    },
  },
  emergency: {
    phoneUrlPrefix: 'tel:',
    defaultContactLabel: 'Trusted family member',
  },
  security: {
    requestBodyLimit: '100kb',
    requestTimeoutMs: 15_000,
    rateLimitWindowMs: 900_000,
    rateLimitMax: 100,
  },
  auth: {
    mpinLength: 4,
    otpLength: 6,
    otpResendCooldownSeconds: 60,
    philippineMobilePattern: '^\\+639\\d{9}$',
    minPasswordLength: 8,
    maxPasswordLength: 72,
    emailMaxLength: 254,
    emailPattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
    backendConnectionError: 'Unable to connect your account to Nona.',
  },
  profile: {
    maxFullNameLength: 120,
  },
} as const;

export const CONTENT = {
  en: {
    greeting: 'Good morning', subtitle: 'Let us take this one safe step at a time.', today: 'Today',
    balance: 'Check my balance', pay: 'Pay someone', load: 'Buy load', focus: 'Your safe focus',
    recent: 'Recent activity', noActivity: 'No activity yet', emergency: 'I need help',
    navHome: 'Home', navInbox: 'Inbox', navQr: 'QR', navTransactions: 'Transactions', navProfile: 'Profile',
    inboxTitle: 'Inbox', inboxEmpty: 'No new messages', inboxDescription: 'Important account updates will appear here.',
    qrTitle: 'Scan or show QR', qrDescription: 'Use QR safely for payments and receiving money.', scanQr: 'Scan QR code', showQr: 'Show my QR',
    transactionsTitle: 'Transactions', transactionsEmpty: 'No transactions yet', transactionsDescription: 'Your completed activity will appear here.',
    profileTitle: 'Profile and settings', profileDescription: 'Manage your account and accessibility preferences.',
    emergencyDescription: 'Call your trusted family member', settings: 'Settings', language: 'Language',
    voiceGuidance: 'Voice guidance', highContrast: 'High contrast', speak: 'Read aloud',
    protected: 'Protected by Nona', sampleTransaction: 'No transactions to review',
    welcome: 'Bank with confidence', loginTitle: 'Welcome back', signupTitle: 'Create your Nona account',
    email: 'Email address', password: 'Password', confirmPassword: 'Confirm password',
    mobileNumber: 'Mobile number', otp: 'Verification code', mpin: '4-digit MPIN', confirmMpin: 'Confirm MPIN',
    fullName: 'Full name', emergencyContact: 'Emergency contact', sendCode: 'Send code', verifyCode: 'Verify code',
    setMpin: 'Set MPIN', enterMpin: 'Enter MPIN', resendCode: 'Resend code', resendIn: 'Resend in', continue: 'Continue', back: 'Back',
    accountReady: 'Your account is ready.', forgotMpin: 'Forgot MPIN?', loginWithEmail: 'Use email instead',
    login: 'Log in', signup: 'Sign up', noAccount: "I don't have an account", haveAccount: 'I already have an account',
    authSubtitle: 'Your safe, simple banking companion.', signingIn: 'Signing in...', creatingAccount: 'Creating account...',
    passwordHint: 'Use at least 8 characters.', logout: 'Log out', logoutConfirmTitle: 'Log out of Nona?', logoutConfirmMessage: 'You can sign in again at any time.', cancel: 'Cancel', confirmationSent: 'Check your email to confirm your account.',
    invalidEmail: 'Enter a valid email address.', passwordMismatch: 'Passwords do not match.', showPassword: 'Show', hidePassword: 'Hide',
    requiredField: 'This field is required.', emailTooLong: 'Email address is too long.', passwordTooLong: 'Password is too long.',
    philippineMobileInvalid: 'Enter a valid Philippine mobile number starting with +63 (for example, +639171234567).',
    backendConnectionTitle: 'Account connection needs attention',
  },
  tl: {
    greeting: 'Magandang umaga', subtitle: 'Isang ligtas na hakbang bawat pagkakataon.', today: 'Ngayon',
    balance: 'Tingnan ang balanse', pay: 'Magbayad', load: 'Bumili ng load', focus: 'Ligtas na gabay',
    recent: 'Kamakailang gawain', noActivity: 'Wala pang gawain', emergency: 'Kailangan ko ng tulong',
    navHome: 'Bahay', navInbox: 'Inbox', navQr: 'QR', navTransactions: 'Mga transaksyon', navProfile: 'Profile',
    inboxTitle: 'Inbox', inboxEmpty: 'Walang bagong mensahe', inboxDescription: 'Lalabas dito ang mahahalagang update sa account.',
    qrTitle: 'Mag-scan o magpakita ng QR', qrDescription: 'Gamitin ang QR nang ligtas para sa bayad at pagtanggap ng pera.', scanQr: 'Mag-scan ng QR code', showQr: 'Ipakita ang aking QR',
    transactionsTitle: 'Mga transaksyon', transactionsEmpty: 'Wala pang transaksyon', transactionsDescription: 'Lalabas dito ang iyong mga natapos na gawain.',
    profileTitle: 'Profile at mga setting', profileDescription: 'Pamahalaan ang iyong account at accessibility preferences.',
    emergencyDescription: 'Tawagan ang iyong pamilya', settings: 'Mga setting', language: 'Wika',
    voiceGuidance: 'Gabay sa boses', highContrast: 'Mataas na contrast', speak: 'Basahin nang malakas',
    protected: 'Protektado ng Nona', sampleTransaction: 'Walang transaksyon na susuriin',
    welcome: 'Ligtas na pagbabangko', loginTitle: 'Maligayang pagbabalik', signupTitle: 'Gumawa ng Nona account',
    email: 'Email address', password: 'Password', confirmPassword: 'Kumpirmahin ang password',
    mobileNumber: 'Mobile number', otp: 'Verification code', mpin: '4-digit MPIN', confirmMpin: 'Kumpirmahin ang MPIN',
    fullName: 'Buong pangalan', emergencyContact: 'Emergency contact', sendCode: 'Magpadala ng code', verifyCode: 'I-verify ang code',
    setMpin: 'Magtakda ng MPIN', enterMpin: 'Ilagay ang MPIN', resendCode: 'Magpadala muli', resendIn: 'Magpadala muli sa', continue: 'Magpatuloy', back: 'Bumalik',
    accountReady: 'Handa na ang iyong account.', forgotMpin: 'Nakalimutan ang MPIN?', loginWithEmail: 'Gumamit ng email',
    login: 'Mag-log in', signup: 'Mag-sign up', noAccount: 'Wala pa akong account', haveAccount: 'May account na ako',
    authSubtitle: 'Ang iyong ligtas at simpleng kasama sa pagbabangko.', signingIn: 'Naglolog in...', creatingAccount: 'Gumagawa ng account...',
    passwordHint: 'Gumamit ng hindi bababa sa 8 karakter.', logout: 'Mag-log out', logoutConfirmTitle: 'Mag-log out sa Nona?', logoutConfirmMessage: 'Maaari kang mag-log in muli anumang oras.', cancel: 'Kanselahin', confirmationSent: 'Tingnan ang iyong email upang kumpirmahin ang account.',
    invalidEmail: 'Maglagay ng wastong email address.', passwordMismatch: 'Hindi magkapareho ang mga password.', showPassword: 'Ipakita', hidePassword: 'Itago',
    requiredField: 'Kailangang punan ang field na ito.', emailTooLong: 'Masyadong mahaba ang email address.', passwordTooLong: 'Masyadong mahaba ang password.',
    philippineMobileInvalid: 'Maglagay ng wastong Philippine mobile number na nagsisimula sa +63 (halimbawa, +639171234567).',
    backendConnectionTitle: 'Kailangan ng pansin ang koneksyon ng account',
  },
  ceb: {
    greeting: 'Maayong buntag', subtitle: 'Usa ka luwas nga lakang matag higayon.', today: 'Karong adlawa',
    balance: 'Tan-awa ang balanse', pay: 'Bayad', load: 'Palit og load', focus: 'Luwas nga giya',
    recent: 'Bag-ong kalihokan', noActivity: 'Wala pay kalihokan', emergency: 'Kinahanglan ko og tabang',
    navHome: 'Balay', navInbox: 'Inbox', navQr: 'QR', navTransactions: 'Mga transaksyon', navProfile: 'Profile',
    inboxTitle: 'Inbox', inboxEmpty: 'Walay bag-ong mensahe', inboxDescription: 'Ang importante nga update sa account makita dinhi.',
    qrTitle: 'I-scan o ipakita ang QR', qrDescription: 'Gamita ang QR nga luwas para sa bayad ug pagdawat og kwarta.', scanQr: 'I-scan ang QR code', showQr: 'Ipakita ang akong QR',
    transactionsTitle: 'Mga transaksyon', transactionsEmpty: 'Wala pay transaksyon', transactionsDescription: 'Ang imong nahuman nga kalihokan makita dinhi.',
    profileTitle: 'Profile ug mga setting', profileDescription: 'Giyahe ang imong account ug accessibility preferences.',
    emergencyDescription: 'Tawagi ang imong pamilya', settings: 'Mga setting', language: 'Pinulongan',
    voiceGuidance: 'Giya sa tingog', highContrast: 'Kusog nga contrast', speak: 'Basaha og kusog',
    protected: 'Gipanalipdan sa Nona', sampleTransaction: 'Walay transaksyon nga susihon',
    welcome: 'Luwas nga banking', loginTitle: 'Maayong pagbalik', signupTitle: 'Paghimo og Nona account',
    email: 'Email address', password: 'Password', confirmPassword: 'Kumpirmahi ang password',
    mobileNumber: 'Mobile number', otp: 'Verification code', mpin: '4-digit MPIN', confirmMpin: 'Kumpirmahi ang MPIN',
    fullName: 'Tibuok nga ngalan', emergencyContact: 'Emergency contact', sendCode: 'Ipadala ang code', verifyCode: 'I-verify ang code',
    setMpin: 'Magtakda og MPIN', enterMpin: 'Ibutang ang MPIN', resendCode: 'Ipadala pag-usab', resendIn: 'Ipadala pag-usab sa', continue: 'Padayon', back: 'Balik',
    accountReady: 'Andam na ang imong account.', forgotMpin: 'Nakalimot sa MPIN?', loginWithEmail: 'Gamita ang email',
    login: 'Log in', signup: 'Sign up', noAccount: 'Wala koy account', haveAccount: 'Aduna na koy account',
    authSubtitle: 'Ang imong luwas ug sayon nga kauban sa banking.', signingIn: 'Nag-log in...', creatingAccount: 'Naghimo og account...',
    passwordHint: 'Gamita ang labing menos 8 ka karakter.', logout: 'Log out', logoutConfirmTitle: 'Mag-log out sa Nona?', logoutConfirmMessage: 'Makabalik ka og log in bisan kanus-a.', cancel: 'Kansela', confirmationSent: 'Tan-awa ang imong email aron kumpirmahon ang account.',
    invalidEmail: 'Ibutang ang hustong email address.', passwordMismatch: 'Dili magkapareho ang mga password.', showPassword: 'Ipakita', hidePassword: 'Tagoa',
    requiredField: 'Kinahanglan pun-an kini nga field.', emailTooLong: 'Sobra kataas ang email address.', passwordTooLong: 'Sobra kataas ang password.',
    philippineMobileInvalid: 'Ibutang ang hustong Philippine mobile number nga nagsugod sa +63 (pananglitan, +639171234567).',
    backendConnectionTitle: 'Kinahanglan susihon ang koneksyon sa account',
  },
} as const;

export type Language = (typeof NONA_CONFIG.app.supportedLanguages)[number];
export type TransactionType = (typeof NONA_CONFIG.transactions.types)[number];
export type ContentKey = keyof typeof CONTENT.en;
